### ISSUE TITLE
alsa usb problem

### ISSUE THREAD

**Issue by texstar** [alsa-project/alsa-lib#59] opened 2020-06-14 15:42 UTC
Plugging in a usb microphone causes pulse audio to crash with alsa-lib 1.2.3.

**Comment by texstar** [comment] 2020-06-14 15:44
Intenal sound device = OK
USB device = Fail

Using from USB to external DAC in a amplifier by default so I have to use the line input from the amplifier.

**Comment by perexg** [comment] 2020-06-14 20:47
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1846742

**Comment by perexg** [comment] 2020-06-15 13:10
It would be nice, if you can help to debug this strange thing. I cannot reproduce your problem here.

**Comment by perexg** [comment] 2020-06-19 19:07
fixed in 1.2.3.1

**Closed by perexg** 2020-06-19 19:07 UTC
